config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources 'contacts', only: [:new, :create]
  resources :contacts, :courts, :meetings, :trainers, :shops, :offers, :matchs, :players
  resources :users do
    resource :profile
  end

  root 'pages#home'

  get '/about' => 'pages#about'
  get '/levels' => 'pages#levels'
  get '/clubs' => 'pages#clubs'
  get '/rules' => 'pages#rules'
#  get '/trainers' => 'pages#trainers'
  get 'players' => 'users#index'



  get 'courts/new'
  get 'courts/create'
  get 'courts/show'
  get 'courts/edit'
  get 'courts/index'
  get 'courts/update'
  get 'courts/destroy'

  get 'groups/index'
  get 'groups/new'
  get 'groups/create'
  get 'groups/show'
  get 'groups/edit'
  get 'groups/update'
  get 'groups/destroy'
  
  get 'invitations/index'
  get 'invitations/show'
  get 'invitations/edit'
  get 'invitations/update'
  get 'invitations/new'
  get 'invitations/destroy'

  get 'trainers/new'
  get 'trainers/create'
  get 'trainers/show'
  get 'trainers/edit'
  get 'trainers/index'
  get 'trainers/update'
  get 'trainers/destroy'

  get 'offers/new'
  get 'offers/create'
  get 'offers/show'
  get 'offers/edit'
  get 'offers/index'
  get 'offers/update'
  get 'offers/destroy'

  get 'players/new'
  get 'players/create'
  get 'players/show'
  get 'players/edit'
  get 'players/index'
  get 'players/update'
  get 'players/destroy'

  get 'matchs/new'
  get 'matchs/create'
  get 'matchs/show'
  get 'matchs/edit'
  get 'matchs/index'
  get 'matchs/update'
  get 'matchs/destroy'

  get 'meetings/new'
  get 'meetings/create'
  get 'meetings/show'
  get 'meetings/edit'
  get 'meetings/index'
  get 'meetings/update'
  get 'meetings/destroy'
 
  get 'shops/new'
  get 'shops/create'
  get 'shops/show'
  get 'shops/edit'
  get 'shops/update'
  get 'shops/index'
  get 'shops/destroy'


  devise_for :users, controllers: { registrations: 'users/registrations' }
  

  
end

app/models/category.rb
class Category < ActiveRecord::Base
	 belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/models/court.rb
class Court < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/match_type.rb
class MatchType < ActiveRecord::Base
	has_many :users
end

app/models/nation.rb
class Nation < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/ranking_type.rb
class RankingType < ActiveRecord::Base
has_many :users
end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  has_many :match_type
  has_many :ranking_type
  has_many :matchs

  after_initialize :set_defaults

  validates_presence_of :first_name, :last_name
  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+([a-zA-Z]|\d)*\Z/ }


  attr_accessor :stripe_card_token 
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end

  def full_name
    self.first_name + " " + self.last_name
  end
  
  private

    def set_defaults
#      self.role ||= 'player'
    end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/court_helper.rb
module CourtHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  def gender
    if @user.profile.gender == "Female"
      "<i class='fa fa-code'></i>".html_safe
    elsif @user.profile.match_type == "Male"
      "<i class='fa fa-lightbulb-o'></i>".html_safe
    end 
  end

#  def match_type
#    if @user.profile.match_type == "Males"
#      "<i class='fa fa-code'></i>".html_safe
#    elsif @user.profile.match_type == "Females"
#      "<i class='fa fa-lightbulb-o'></i>".html_safe
#    elsif @user.profile.match_type == "Males & Mix"
#      "<i class='fa fa-dollar'></i>".html_safe
#    elsif @user.profile.match_type == "Females & Mix"
#      "<i class='fa fa-dollar'></i>".html_safe
#    end 
#  end

end

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
<h4><b>List of your padel's players groups</b></h4>

<div class='col-md-6'>
  <div class='well'>
 <p class="text-sd-left text-justify"> List of your padel's players groups, acting as leader and owber or as follower member. You can send messages and invitations to this groups. Ypou can create new groups, selecting member of your club or your local common players for facilitating your communications.
 </p>
 </div><!-- well -->
</div><!-- md-6 -->  
<div class='col-md-6'>  
<div class='well' style='height:300px'>
    <form>
    <div class='col-md-3' style='width:70%'>
      <b>Name:</b>&nbsp; <input type="text" name="name" size='25' value='name of the new group' type='text'>
  <p><br/></p>
  <table style='margin-top:25px; padding-top:25px;'>
    <tr><td style='margin-top:25px;'><b>Description:</b></td></tr>
    <tr><td><textarea cols="80" rows='6' name="description"></textarea></td></tr>
  </table>
</small>
     <p class="text-sd-left text-justify" style='margin-top:5px;'><%= link_to 'Create a New Group', groups_new_path, class:'btn btn-success pull-right btn-space-left' %>
     </p>
   </form>
 </div><!-- row -->
  </div><!-- well -->
</div><!-- md-6 -->


    <%# if @matchs.exists? %>  
    <table class='table table-striped' style='font-size:11px;'>
      <tr>
        <th>Name</th>
        <th>Administrator</th>
        <th>Description</th>
        <th>Action</th>
      </tr>
<%# @matchs.each do |match| %>
      <tr>
      <td><%#= match.court %>CN Montjuïc Padelers</td>
      <td><%#= match.player3 %><a href='http://padels.org/users/2'>John</a><%#= match.player4 %></td>
      <td><%#= match.description %>Grup of members that practice padel at CN Montjuic.</td>
      <td><%#= match.description %>Send a message</td>
      </tr>
      <%# end %>
  <tr>
      <td><%#= match.court %>Padel in Montjuïc</td>
      <td><%#= match.player1 %><a href='http://padels.org/users/4'>Oscar</a><%#= match.player2 %></td>
      <td><%#= match.description %>Padel players that play padel in Montjuïc mountaine: Picornell, CN, Pompeia,...</td>
      <td><%#= match.description %>Send a message</td>
      </tr>
    </table>
      <%#= will_paginate @matchs %>
    <%# else %>
    <P><small> This are examples of unofficial formed groups.</small></P>
   <%# end %>

</div>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>

app/views/groups/show.html.erb
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>

app/views/groups/update.html.erb
<h1>Groups#update</h1>
<p>Find me in app/views/groups/update.html.erb</p>