config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources 'contacts', only: [:new, :create]
  resources :contacts, :courts, :meetings, :trainers, :shops, :offers, :matchs, :players
  resources :users do
    resource :profile
  end

  root 'pages#home'

  get '/about' => 'pages#about'
  get '/levels' => 'pages#levels'
  get '/clubs' => 'pages#clubs'
  get '/rules' => 'pages#rules'
#  get '/trainers' => 'pages#trainers'
  get 'players' => 'users#index'



  get 'courts/new'
  get 'courts/create'
  get 'courts/show'
  get 'courts/edit'
  get 'courts/index'
  get 'courts/update'
  get 'courts/destroy'

  get 'groups/index'
  get 'groups/new'
  get 'groups/create'
  get 'groups/show'
  get 'groups/edit'
  get 'groups/update'
  get 'groups/destroy'
  
  get 'invitations/index'
  get 'invitations/show'
  get 'invitations/edit'
  get 'invitations/update'
  get 'invitations/new'
  get 'invitations/destroy'

  get 'trainers/new'
  get 'trainers/create'
  get 'trainers/show'
  get 'trainers/edit'
  get 'trainers/index'
  get 'trainers/update'
  get 'trainers/destroy'

  get 'offers/new'
  get 'offers/create'
  get 'offers/show'
  get 'offers/edit'
  get 'offers/index'
  get 'offers/update'
  get 'offers/destroy'

  get 'players/new'
  get 'players/create'
  get 'players/show'
  get 'players/edit'
  get 'players/index'
  get 'players/update'
  get 'players/destroy'

  get 'matchs/new'
  get 'matchs/create'
  get 'matchs/show'
  get 'matchs/edit'
  get 'matchs/index'
  get 'matchs/update'
  get 'matchs/destroy'

  get 'meetings/new'
  get 'meetings/create'
  get 'meetings/show'
  get 'meetings/edit'
  get 'meetings/index'
  get 'meetings/update'
  get 'meetings/destroy'
 
  get 'shops/new'
  get 'shops/create'
  get 'shops/show'
  get 'shops/edit'
  get 'shops/update'
  get 'shops/index'
  get 'shops/destroy'


  devise_for :users, controllers: { registrations: 'users/registrations' }
  

  
end

app/models/category.rb
class Category < ActiveRecord::Base
	 belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/models/court.rb
class Court < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/match_type.rb
class MatchType < ActiveRecord::Base
	has_many :users
end

app/models/nation.rb
class Nation < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/ranking_type.rb
class RankingType < ActiveRecord::Base
has_many :users
end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  has_many :match_type
  has_many :ranking_type
  has_many :matchs

  after_initialize :set_defaults

  validates_presence_of :first_name, :last_name
  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+([a-zA-Z]|\d)*\Z/ }


  attr_accessor :stripe_card_token 
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end

  def full_name
    self.first_name + " " + self.last_name
  end
  
  private

    def set_defaults
#      self.role ||= 'player'
    end


end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def new
  end

  def destroy
  end
end

app/helpers/court_helper.rb
module CourtHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/invitations/_form.html.erb
<%= form_for @profile, url: user_profile_path, 
:html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :club %>
    <%= f.text_field :club, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%#= f.label :ranking_type %>
    <%#= f.select :ranking_type, Ranking_type.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %>
  </div>
  <div class="form-group">
  <%= radio_button_tag(:gender, 'Female') %><%= label_tag(:gender, "Female") %>
  <%= radio_button_tag(:gender, 'Male') %><%= label_tag(:gender, "Male") %>
  </div>
  <div class="form-group">
    <%= f.label :match_type %>
   <%= f.select :match_type, Match_type.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control' %>
    <%= f.select :category, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :level %>
    <%= f.text_field :level, class: 'form-control' %>
    <%= f.select :level, Level.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :score_wins %>
    <%= f.text_field :score_wins, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :score_plays %>
    <%= f.text_field :score_plays, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :nation %>
    <%= f.text_field :nation, class: 'form-control' %>
    <%= f.select :nation, Nation.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select one'}, class:'form-control' %>   
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/invitations/destroy.html.erb
<h1>Invitations#destroy</h1>
<p>Find me in app/views/invitations/destroy.html.erb</p>

app/views/invitations/edit.html.erb
<h1>Invitations#edit</h1>
<p>Find me in app/views/invitations/edit.html.erb</p>

app/views/invitations/index.html.erb
<div class='col-md-6'>
  <div class='well'>
    <h4><b><i>Invite players to play a Match!</i></b></h4>
 List of invitations for playing a match. Before sending an invitation to a group of players you choose the selection criteria (open or social, category, level, type of match,...).
 <br/>Remember! your email message will be sent initially to the first 25 players of your selected target group. This number will increase with your number of your played matches.
 <br/>You will receive From players, contacted via email or through here, answers and proposals for arranging easily and quickly the match. If you know some details (days, hours, court,...) you can publish them for facilitating other players to contact you and progress quickly to the match organisation. When the match has four players, you have to close the match invitation.
 </p>
 </div><!-- well -->
</div><!-- md-6 -->  
<div class='col-md-6'>  
  <div class='well' style='height:300px'>
    <form>
    <small>
    <p><b>Match type:</b>
    &nbsp;<input type="checkbox" name="MatchType" value="FEMALE"> Female  
    &nbsp;<input type="checkbox" name="MatchType" value="MALE"> Male  
    &nbsp;<input type="checkbox" name="MatchType" value="MIX" checked="checked"> Mix  
    &nbsp;<input type="checkbox" name="MatchType" value="FMP"> Female-Male pairs  
    </p>
    <p><b>Ranking type:</b>
    &nbsp;<input type="checkbox" name="RankingType" value="OSL" checked="checked"> Open Social Ladder  
    &nbsp;<input type="checkbox" name="RankingType" value="COM"> Competitive match
  </p>     
  <select style='margin-bottom:10px; margin-right:25px;'>
          <option value="">Age category</option>
          <option value="1">1.Infantil +10</option>
          <option value="2">2.Juvenil +15</option>
          <option value="3">3.Junior +20</option>
          <option value="4">4.Junior +25</option>
          <option value="5">5.Senior +30</option>
          <option value="6">6.Senior +35</option>
          <option value="7">7.Senior +40</option>
          <option value="8">8.Sebior +45</option>
          <option value="9">9.Senior +50</option>
          <option value="10">10.Senior +55</option>
          <option value="11">11.Veteran +60</option>
          <option value="12">12.Veteran +65</option>
          <option value="13">13.Veteran +70</option>
    </select>
    <select style='margin-bottom:10px;'>
          <option value="">Player level</option>
          <option value="1-2">1-2.Debutant-Novice</option>
          <option value="3">3.Intermediate-Competent</option>
          <option value="4">4.Qualified-Advanced</option>
          <option value="5">5.Expert-Master</option>
          <option value="6-7">6-7.Semi & Professionals WPT</option>
    </select>
  <p><b>Invitation Message:</b></p>
    <textarea cols="80" rows='6' name="message"></textarea>
</small>
<br/>
<p class="text-sd-left text-justify"><%= link_to 'Submit Invitation to 27 players', new_contact_path, class:'btn btn-success pull-right btn-space-left' %></p>
  </form>
  </div><!-- well -->
</div><!-- md-6 -->



    <%# if @matchs.exists? %>  
    <table class='table table-striped' style='font-size:11px;'>
      <tr>
        <th>Date</th>
        <th>Court</th>
        <th>Ranking Type</th>
        <th>Match Type</th>
        <th>Age Category</th>
        <th>Level Player</th>
        <th>Description</th>
        <th>Contact</th>
      </tr>
<%# @matchs.each do |match| %>
      <tr>
      <td><%#= match.date %>20-07-2016</td>
      <td><%#= match.court %>CN Montjuïc or BCN</td>
      <td><%#= match.player1 %>All<%#= match.player2 %></td>
      <td><%#= match.player3 %>--</td>
      <td><%#= match.set1 %>All</td>
      <td><%#= match.set1 %>4.QUALIFIED-ADVANCED</td>
      <td><%#= match.description %>Preferably at the evening >19:00 in anywhere BCN, competitive match and Level 4-5. Contact <a href='http://padels.org/users/2'>me </a>before next Monday.<a href=''>+info</a></td>
      <td><%#= match.date %><a href="/player2">John Pawndoe</a></td>
      </tr>
      <%# end %>
  <tr>
      <td><%#= match.date %>20-06-2016</td>
      <td><%#= match.court %>CN Montjuïc</td>
      <td><%#= match.player1 %>All<%#= match.player2 %></td>
      <td><%#= match.player3 %>--</td>
      <td><%#= match.set1 %>All</td>
      <td><%#= match.set1 %>4.QUALIFIED-ADVANCED</td>
      <td><%#= match.description %>Preferably at the evening >19:00 in anywhere BCN, competitive match and Level 4-5. Contact <a href='http://padels.org/users/2'>me </a>before next Monday.<a href=''>+info</a></td>
      <td><%#= match.date %><a href="/player2">Ferran Cabrer</a></td>
      </tr>
  <tr>
      <td><%#= match.date %>20-06-2016</td>
      <td><%#= match.court %>CN Montjuïc</td>
      <td><%#= match.player1 %>All<%#= match.player2 %></td>
      <td><%#= match.player3 %>--</td>
      <td><%#= match.set1 %>All</td>
      <td><%#= match.set1 %>4.QUALIFIED-ADVANCED</td>
      <td><%#= match.description %>Preferably at the evening >19:00 in anywhere BCN, competitive match and Level 4-5. Contact <a href='http://padels.org/users/2'>me </a>before next Monday.<a href=''>+info</a></td>
      <td><%#= match.date %><a href="/player3">Raul Ruiz</a></td>
      </tr>
    </table>
      <%#= will_paginate @matchs %>
    <%# else %>
    <P><small> This are examples of invitations and played matches because there aren't official matches still.</small></P>
   <%# end %>

</div>

app/views/invitations/new.html.erb
<h1>Invitations#new</h1>
<p>Find me in app/views/invitations/new.html.erb</p>

app/views/invitations/show.html.erb
<h1>Invitations#show</h1>
<p>Find me in app/views/invitations/show.html.erb</p>

app/views/invitations/update.html.erb
<h1>Invitations#update</h1>
<p>Find me in app/views/invitations/update.html.erb</p>