config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources 'contacts', only: [:new, :create]
  resources :contacts, :courts, :meetings, :trainers, :shops, :offers, :matchs, :players
  resources :users do
    resource :profile
  end

  root 'pages#home'

  get '/about' => 'pages#about'
  get '/levels' => 'pages#levels'
  get '/clubs' => 'pages#clubs'
  get '/rules' => 'pages#rules'
#  get '/trainers' => 'pages#trainers'
  get 'players' => 'users#index'



  get 'courts/new'
  get 'courts/create'
  get 'courts/show'
  get 'courts/edit'
  get 'courts/index'
  get 'courts/update'
  get 'courts/destroy'

  get 'groups/index'
  get 'groups/new'
  get 'groups/create'
  get 'groups/show'
  get 'groups/edit'
  get 'groups/update'
  get 'groups/destroy'
  
  get 'invitations/index'
  get 'invitations/show'
  get 'invitations/edit'
  get 'invitations/update'
  get 'invitations/new'
  get 'invitations/destroy'

  get 'trainers/new'
  get 'trainers/create'
  get 'trainers/show'
  get 'trainers/edit'
  get 'trainers/index'
  get 'trainers/update'
  get 'trainers/destroy'

  get 'offers/new'
  get 'offers/create'
  get 'offers/show'
  get 'offers/edit'
  get 'offers/index'
  get 'offers/update'
  get 'offers/destroy'

  get 'players/new'
  get 'players/create'
  get 'players/show'
  get 'players/edit'
  get 'players/index'
  get 'players/update'
  get 'players/destroy'

  get 'matchs/new'
  get 'matchs/create'
  get 'matchs/show'
  get 'matchs/edit'
  get 'matchs/index'
  get 'matchs/update'
  get 'matchs/destroy'

  get 'meetings/new'
  get 'meetings/create'
  get 'meetings/show'
  get 'meetings/edit'
  get 'meetings/index'
  get 'meetings/update'
  get 'meetings/destroy'
 
  get 'shops/new'
  get 'shops/create'
  get 'shops/show'
  get 'shops/edit'
  get 'shops/update'
  get 'shops/index'
  get 'shops/destroy'


  devise_for :users, controllers: { registrations: 'users/registrations' }
  

  
end

app/models/category.rb
class Category < ActiveRecord::Base
	 belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/models/court.rb
class Court < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/level.rb
class Level < ActiveRecord::Base
end

app/models/match_type.rb
class MatchType < ActiveRecord::Base
	has_many :users
end

app/models/nation.rb
class Nation < ActiveRecord::Base
end

app/models/offer.rb
class Offer < ActiveRecord::Base
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/ranking_type.rb
class RankingType < ActiveRecord::Base
has_many :users
end

app/models/shop.rb
class Shop < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  has_many :match_type
  has_many :ranking_type
  has_many :matchs

  after_initialize :set_defaults

  validates_presence_of :first_name, :last_name
  validates :username, uniqueness: true, presence: true, format: { with: /\A[a-zA-Z]+([a-zA-Z]|\d)*\Z/ }


  attr_accessor :stripe_card_token 
  def save_with_payment
    if valid?
      customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
      self.stripe_customer_token = customer.id
      save!
    end
  end

  def full_name
    self.first_name + " " + self.last_name
  end
  
  private

    def set_defaults
#      self.role ||= 'player'
    end


end

app/helpers/court_helper.rb
module CourtHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/match_helper.rb
module MatchHelper
end

app/helpers/offer_helper.rb
module OfferHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/partials/_alerts.html.erb
<!-- Alerts & messages -->
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>

<% if notice %><p class="notice"><%= notice %></p><% end %>
<% if alert %><p class="alert"><%= alert %></p><% end %>

<!-- container Alerts & messages/> -->

app/views/layouts/partials/_footer.html.erb
<div id="enclose">
	<div id="problem">
   
    <div class="container">
    	<p><small>Barcelona-Padelsocial.org Copyright &copy; <%= Time.now.year %>  All Rights Reserved <a href='http://MUFICATA.net'>MUFICATA RTDI SL</a> B-61421830, <I>info AT muficata DOT net</I>, 12 Jaume Fabra, 08004 Barcelona CATALONIA
        </small></p>
    </div>
	
	</div>
</div>

        <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script>window.jQuery || document.write('<script src="javascript/jquery.min.js"><\/script>')</script>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

app/views/layouts/partials/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1' /><![endif]-->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

<meta name="description" content="[Social-Padel.org] platform doe facilitating the practice of padel game in the metropolitan araea of Barcelona. Padel Players can meet, invite and play with other padel players, organising matches and meetings, branding their skills, recording their match results, and much more information: courts where play, shops offering discoutnts, the best trainers and learning sessions,... Platform and community of paddel, padel, pàdel players for facilitating the padel practice in the Barelona metropolitan area." />
<meta name="author" content="MUFICATA RDTI SL & [Social-Sport.org] & Ferran Cabrer i Viiagut">
<%#= favicon_link_tag %>
<link rel="icon" type="image/png" href="http://socialpadel.org/images/spo32.png">



<title>[SocialPadel.org] | <%= @page_title %> | Facilitating Padel in Barcelona</title>

  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>  
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>

  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<!--<link href="/assets/padels.css" rel="stylesheet" type="text/css">-->
<%#= stylesheet_link_tag 'padels', media: 'all', 'data-turbolinks-track' => true %>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>-->
<!-- Bootstrap -->
<!--<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">-->

<!-- styles -->

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<link rel="stylesheet" type="text/css" href="/assets/stylesheets/padels.css.scss">
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>


<meta name="google-site-verification" content="hd3t4aYJeVpUQCOk1A8o3GT9y0S7jWPkd18DrNWFE0s" />

<!-- search engine -->
<link rel="canonical" href="http://[Social-Padel.org]" />


    <!-- sad hack because github pages doesn't support https -->
  <script>
     if (window.location.protocol == "https:") window.location.protocol = "http:"
  </script>
 

   <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/partials/_topnavbar.html.erb
<nav class="navbar navbar-static-top nav-bordered navbar-collapse" id="main-nav-collapse" role="navigation">
  <div class='container'>

    <div class="navbar-header navbar-left" style='align:left; margin:0;'>
      <%= link_to root_path, class: 'navbar-brand' do %>
         <img src='/images/SocialPadel.org300.png' alt:'Facilitating Pàdel in Barcelona', style='float:left; margin-left:10px; height:40px;'/>
      <% end %>
    </div><!-- ./navbar-left -->

    <ul class="nav navbar-nav navbar-right" style='margin:'0px'>
        <%# if user_signed_in? %>
        <li style='font-weight: bold;font-size:'16px'><%= link_to "Players", players_path %></li>
        <li style='font-weight: bold;font-size:'16px'><%= link_to "Matches", matchs_index_path %></li>
        <li style='font-weight: bold;font-size:'16px'><%= link_to "Invitations", invitations_index_path %></li>
        <%# end %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Information <span class="caret"></span></a>
              <ul class="dropdown-menu">

<li style='font-weight: bold;'><a href='/courts#index'>Courts</a></li>
<li style='font-weight: bold;'><a href='/meetings#index'>Meetings</a></li>
<li style='font-weight: bold;'><a href='/trainers#index'>Trainers</a></li>
<li style='font-weight: bold;'><a href='/shops#index'>Shops</a></li>
<li style='font-weight: bold;'><a href='/offers#index'>Offers</a></li>
<li role="separator" class="divider"></li>
<li><%= link_to "Rules", rules_path %></li>
<li><%= link_to "Levels", levels_path %></li>
<li role="separator" class="divider"></li>
<li><%= link_to "About us", about_path %></li>

              </ul>
            </li><!-- ./dropdown -->

        <li style='font-weight: bold;font-size:14px'><%= link_to "Contact Us", new_contact_path %></li>

       <% if user_signed_in? %>
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account <span class="caret"></span></a>
        <ul class="dropdown-menu">        
        <li style='font-weight: bold;font-size:16px'><%= link_to "My Profile", edit_user_registration_path %></li>
        <li style='font-weight: bold;font-size:16px'><%= link_to "My Groups", groups_index_path %></li>
        </ul>
        </li><!-- ./dropdown -->
       <li style='font-weight: bold;font-size:12px'><%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %></li>
        <% else %>
       <li style='font-weight: bold;font-size:12px'><%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %></li>
        <% end %>

	</ul><!-- .7navbar-right -->


</div><!-- container -->
</nav><!-- /.navbar-static-top -->

app/views/layouts/shared/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/shared/_header.html.erb
<div class="grey2"></div>

<div id="header">
  <div class="container">
    <div class="row">
      <div class="grey"></div>
      <a class="col-xs-3 logo pull-left" href="<%= root_url %>">
        <%= image_tag('common/logo.png') %>
        <%= image_tag('common/logo_small.png', class: 'logo-small') %>
      </a>
      <div class="col-xs-9 pull-left">
        <div class="col-xs-6 pull-left">
          <span class="icon icon-search"></span>
          <input type="text" placeholder="Search..."/>
        </div>
        <div class="col-xs-3 avatar pull-right">
          <a href="<%= root_url %>">
            <div class="mask"></div>
            <%= image_tag('common/guest_image.png') %>
          </a>
          <strong>Welcome Guest!</strong>
          <%= link_to "Login", new_user_session_path %> or
          <%= link_to "Register", new_user_registration_path %>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

<div id="main-menu" class="small">
  <div class="container">
    <div class="row">
    </div>
  </div>
</div>

app/views/layouts/shared/_posts.html.erb
<% @posts.each do |post| %>
	<li class="clearfix">
		<div class="ratings">
			<a href="#up" class="up"></a>
			<h1>1178</h1>
			<a href="#down" class="down"></a>
		</div>

		<div class="article-image">
			<div class="mask"></div>
			<img src="https://s3.amazonaws.com/rails-camp-tutorials/pro-rails/ui/article_image.png"/>
		</div>

		<div class="article-desc">
			<h2><%= link_to post.title, topic_post_path(topic_id: post.topic.slug, id: post) %></h2>
			<p><%= post.content %></p>
			<span>By <strong><%= post.user.username %></strong> <%= post.created_at %></span>
		</div>

		<div class="article-stats">
			<ul class="pull-right">
				<li>
					<span class="icon icon-view"></span>
					<h2>347</h2>
				</li>
				<li>
					<span class="icon icon-comment"></span>
					<h2>347</h2>
				</li>
				<li>
					<span class="icon icon-connection"></span>
					<h2>347</h2>
				</li>
			</ul>
		</div>
	</li>
<% end %>